TRUNCATE TABLE marca;
INSERT INTO `marca` VALUES(1, 'Caloi', 1);
INSERT INTO `marca` VALUES(2, 'Soul', 1);
INSERT INTO `marca` VALUES(3, 'GTS', 0);
INSERT INTO `marca` VALUES(4, 'Trek', 1);
INSERT INTO `marca` VALUES(5, 'GT', 1);
INSERT INTO `marca` VALUES(6, 'Felt', 1);
INSERT INTO `marca` VALUES(7, 'Cannondale', 1);
INSERT INTO `marca` VALUES(8, 'Specialized', 1);
INSERT INTO `marca` VALUES(9, 'Focus', 0);